const diccionario = {
	homeTitle: ["Els millors Parcs Naturals de Barcelona!", "Los mejores Parques Naturales de Barcelona!"],
    homeText: ["T'agrada la natura? Has de saber que, encara que visquis a Barcelona oa la seva àrea metropolitana, a prop de la ciutat trobaràs espais naturals que són perfectes per perdre's i gaudir d'un dia a l'aire lliure. En aquest llistat de Salir.com hem recopilat els millors parcs naturals a prop de Barcelona i el més llunyà de tots és a menys d'1 hora i mitja, per tant podràs fer una escapada tranquil·lament d'un dia. Tots aquests espais són ideals per descobrir al costat dels teus amics o família i t'ofereixen bells racons on la natura mostra la millor faceta. Descobreix-los!", "¿Te gusta la naturaleza? Debes saber que, aunque vivas en Barcelona o en su área metropolitana, cerca de la ciudad encontrarás espacios naturales que son perfectos para perderse y disfrutar de un día al aire libre. En este listado de Salir.com hemos recopilado los mejores parques naturales cerca de Barcelona y el más lejano de todos está a menos de 1 hora y media, por tanto, podrás hacer una escapada de un día tranquilamente. Todos estos espacios son ideales para descubrir junto a tus amigos o familia y te ofrecen bellos rincones donde la naturaleza muestra su mejor faceta. ¡Descúbrelos!"],
    collserolaText: ["El Parque de Collserola és un espai natural que compta amb 8000 hectàrees de flora i natura. Aquí trobaràs espècies com alzines, roures, pins, etcètera. És una visita interessant perquè, a més de zones naturals, també t'aniràs trobant amb ermites i esglésies antigues que donen un aire autèntic a la teva visita.", "El Parc de Collserola se trata de un espacio natural que cuenta con 8000 hectáreas de flora y naturaleza. Aquí encontrarás especies como encinas, robles, pinos, etcétera. Es una visita interesante porque, además de zonas naturales, también te irás encontrando con ermitas e iglesias antiguas que le dan un aire auténtico a tu visita."],
    deltaLlobregatText: ["Continuem coneixent els parcs naturals de Barcelona per conèixer, ara, un altre espai que és molt proper a la ciutat comtal; concretament, a la zona del Baix Llobregat. El Delta del Llobregat és un racó natural que destaca pel seu valor ecològic i per la biodiversitat que hi ha, tant de flora com de fauna.", "Seguimos conociendo los parques naturales de Barcelona para conocer, ahora, otro espacio que está muy próximo a la ciudad condal; concretamente, en la zona del Baix Llobregat. El Delta del Llobregat es un rincón natural que destaca por su valor ecológico y por la biodiversidad que existe, tanto de flora como de fauna."],
    montserratTitle:["Muntanya de Montserrat", "Montaña de Montserrat"],
    montserratText:["Un altre dels millors parcs naturals a prop de Barcelona és a 30 quilòmetres de la ciutat, cap a l'interior. Parlem del parc de Montserrat, un espai natural que compta amb una de les muntanyes més sorprenents de tot el país. Es tracta d'un lloc ideal per als amants de l'escalada, del senderisme o de les muntanyes ja que, agafant qualsevol de les seves rutes, us meravellareu amb paisatges sorprenents i amb unes vistes d'infart.", "Otro de los mejores parques naturales cerca de Barcelona se encuentra a 30 kilómetros de la ciudad, hacia el interior. Hablamos del parque de Montserrat, un espacio natural que cuenta con una de las montañas más sorprendentes de todo el país. Se trata de un lugar ideal para los amantes de la escalada, del senderismo o de las montañas ya que, cogiendo cualquiera de sus rutas, te maravillarás con paisajes asombrosos y con unas vistas de infarto."],
    pantaVallvidreraTitle:["Pantà de Vallvidrera", "Pantano de Vallvidrera"],
    pantaVallvidreraText:["Un dels parcs naturals de Barcelona ciutat i que val la pena conèixer és el Pantà de Vallvidrera, un embassament hidràulic que està situat al barri que li dóna nom (Vallvidrera) i on podràs trobar un espai natural perfecte per anar amb la teva família o amb amics.", "Uno de los parques naturales de Barcelona ciudad y que merece la pena conocer es el Pantano de Vallvidrera, un embalse hidráulico que está situado en el barrio que le da nombre (Vallvidrera) y donde podrás encontrar un espacio natural perfecto para ir con tu familia o con amigos."],
    parcGarrafTitle:["Parc Natural del Garraf", "Parque Natural del Garraf"],
    parcGarrafText:["El Parc Natural del Garraf és un paisatge sorprenent que està creat per roques càrstiques i que compten amb una vegetació variada que és pròpia d'aquesta zona. Es troba entre les comarques del Garraf, del Baix Llobregat i de l'Alt Penedès, un parc molt proper al mar i que, des de molts punts, ofereix imponents vistes al Mediterrani.", "El Parque Natural del Garraf es un paisaje sorprendente que está creado por rocas cársticas y que cuentan con una variada vegetación que es propia de esta zona. Se encuentra entre las comarcas del Garraf, del Baix Llobregat y del Alt Penedés, un parque que está muy próximo al mar y que, desde muchos puntos, ofrece imponentes vistas al Mediterráneo."],
    parcMontsenyTitle:["Muntanya de Montserrat", "Montaña de Montserrat"],
    parcMontsenyText:["Al Montseny trobareu tres conjunts de muntanyes que són molt destacats: el Puig Drau, les Agudes, els Matagalls i el Turó de l'Home. Ideals per fer senderisme, esports de muntanya, rutes amb bicicleta... És un espai perfecte per sortir de la rutina de la ciutat i gaudir d'un oasi de natura a menys d'1 hora de Barcelona.", "En el Montseny encontrarás tres conjuntos de montañas que son muy destacados: el Puig Drau, les Agudes, els Matagalls i el Turó de l'Home. Ideales para hacer senderismo, deportes de montaña, rutas en bicicleta... Es un espacio perfecto para salir de la rutina de la ciudad y disfrutar de un oasis de naturaleza a menos de 1 hora de Barcelona."],
    pedraforcaText:["Una mica més lluny que les anteriorment esmentades però, encara, dins de la província de Barcelona és on hi ha El Pedraforca, una muntanya que és al Berguedà i que és tot un símbol de Catalunya. Tant la muntanya com els voltants són ideals per descobrir fent rutes de senderisme, passejades amb bici, etcètera.", "Un poco más lejos que las anteriormente mencionadas pero, aún, dentro de la provincia de Barcelona es donde se encuentra El Pedraforca, una montaña que está en el Berguedà y que es todo un símbolo de Cataluña. Tanto la montaña como los alrededores son ideales para descubrir haciendo rutas de senderismo, paseos en bici, etcétera."],
    santLlorencLaMolaTitle:["Parc Natural de Sant Llorenç i La Mola", "Parque Natural de San Lorenzo y La Mola"],
    santLlorencLaMolaText:["Aquest parc es troba a menys de 30 minuts de Barcelona i compta amb la Mola, una muntanya ideal per pujar amb familiars o amics ja que és una senzilla ascensió de, com a molt, 1 hora de durada. Al cim d'aquesta muntanya us trobareu amb un restaurant així com unes belles vistes panoràmiques que us deixaran sense alè.", "Este parque se encuentra a menos de 30 minutos de Barcelona y cuenta con la Mola, una montaña ideal para subir con familiares o amigos ya que es una sencilla ascensión de, como mucho, 1 hora de duración. En la cima de esta montaña te encontrarás con un restaurante así como unas bellas vistas panorámicas que te dejarán sin aliento."],
}

export default diccionario;